//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmwAceHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmwAceHelper.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_DIRECTION {
            get {
                return ResourceManager.GetString("COLUMN_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_MEMO {
            get {
                return ResourceManager.GetString("COLUMN_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mario X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_PLAYER_X {
            get {
                return ResourceManager.GetString("COLUMN_PLAYER_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mario Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_PLAYER_Y {
            get {
                return ResourceManager.GetString("COLUMN_PLAYER_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_SHELL {
            get {
                return ResourceManager.GetString("COLUMN_SHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_SHELL_X {
            get {
                return ResourceManager.GetString("COLUMN_SHELL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shell Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_SHELL_Y {
            get {
                return ResourceManager.GetString("COLUMN_SHELL_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yoshi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_YOSHI {
            get {
                return ResourceManager.GetString("COLUMN_YOSHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yoshi X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_YOSHI_X {
            get {
                return ResourceManager.GetString("COLUMN_YOSHI_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yoshi Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COLUMN_YOSHI_Y {
            get {
                return ResourceManager.GetString("COLUMN_YOSHI_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMW ACE Helper has crashed.
        ///Please send the crash report file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CRASHED {
            get {
                return ResourceManager.GetString("CRASHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DIALOG_OPEN {
            get {
                return ResourceManager.GetString("DIALOG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DIALOG_SAVE_AS {
            get {
                return ResourceManager.GetString("DIALOG_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DIRECTION_LEFT {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DIRECTION_RIGHT {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT_COPY {
            get {
                return ResourceManager.GetString("EDIT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT_DELETE {
            get {
                return ResourceManager.GetString("EDIT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Insert new row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT_INSERT {
            get {
                return ResourceManager.GetString("EDIT_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT_PASTE {
            get {
                return ResourceManager.GetString("EDIT_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT_REDO {
            get {
                return ResourceManager.GetString("EDIT_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT_UNDO {
            get {
                return ResourceManager.GetString("EDIT_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_EXIT {
            get {
                return ResourceManager.GetString("FILE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_NEW {
            get {
                return ResourceManager.GetString("FILE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_OPEN {
            get {
                return ResourceManager.GetString("FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_RECENT {
            get {
                return ResourceManager.GetString("FILE_RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_SAVE {
            get {
                return ResourceManager.GetString("FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save _As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_SAVE_AS {
            get {
                return ResourceManager.GetString("FILE_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LANGUAGE_ENGLISH {
            get {
                return ResourceManager.GetString("LANGUAGE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LANGUAGE_JAPANESE {
            get {
                return ResourceManager.GetString("LANGUAGE_JAPANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE {
            get {
                return ResourceManager.GetString("MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down 16 pixels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_16PX_DOWN {
            get {
                return ResourceManager.GetString("MOVE_16PX_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move 16 pixels to the left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_16PX_LEFT {
            get {
                return ResourceManager.GetString("MOVE_16PX_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move 16 pixels to the right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_16PX_RIGHT {
            get {
                return ResourceManager.GetString("MOVE_16PX_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up 16 pixels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_16PX_UP {
            get {
                return ResourceManager.GetString("MOVE_16PX_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move down 1 pixel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_1PX_DOWN {
            get {
                return ResourceManager.GetString("MOVE_1PX_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move 1 pixel to the left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_1PX_LEFT {
            get {
                return ResourceManager.GetString("MOVE_1PX_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move 1 pixel to the right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_1PX_RIGHT {
            get {
                return ResourceManager.GetString("MOVE_1PX_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move up 1 pixel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_1PX_UP {
            get {
                return ResourceManager.GetString("MOVE_1PX_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move 256 pixels to the left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_256PX_LEFT {
            get {
                return ResourceManager.GetString("MOVE_256PX_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move 256 pixels to the right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MOVE_256PX_RIGHT {
            get {
                return ResourceManager.GetString("MOVE_256PX_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your changes have not been saved.
        ///Do you want to save the changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SAVE_CHANGES {
            get {
                return ResourceManager.GetString("SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Thumbnail View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string THUMBNAIL {
            get {
                return ResourceManager.GetString("THUMBNAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _100% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string THUMBNAIL_100_PERCENT {
            get {
                return ResourceManager.GetString("THUMBNAIL_100_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _50% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string THUMBNAIL_50_PERCENT {
            get {
                return ResourceManager.GetString("THUMBNAIL_50_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _75% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string THUMBNAIL_75_PERCENT {
            get {
                return ResourceManager.GetString("THUMBNAIL_75_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMW ACE Helper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Untitled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UNTITLED {
            get {
                return ResourceManager.GetString("UNTITLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Zoom View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZOOM {
            get {
                return ResourceManager.GetString("ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _4x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZOOM_4X {
            get {
                return ResourceManager.GetString("ZOOM_4X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _5x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZOOM_5X {
            get {
                return ResourceManager.GetString("ZOOM_5X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _6x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZOOM_6X {
            get {
                return ResourceManager.GetString("ZOOM_6X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _7x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZOOM_7X {
            get {
                return ResourceManager.GetString("ZOOM_7X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _8x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZOOM_8X {
            get {
                return ResourceManager.GetString("ZOOM_8X", resourceCulture);
            }
        }
    }
}
